num_cols_dict_fs = {'df_horiz': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Curve Radius (ft)',
                                 'Deflection Angle (deg)'],
                    'df_vert': ['VPI/Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Back Grade (%)',
                                'Back Length (ft)', 'Forward Grade (%)', 'Forward Length (ft)'],
                    'df_areatype': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)'],
                    'df_funcclass': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)'],
                    'df_aadt': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Year', 'AADT (vpd)'],
                    'df_lane': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Priority','Start Width (ft)',
                                'End Width (ft)'],
                    'df_laneoffset': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Full Offset (ft)',
                                      'Begin Loc. Full Width (Sta. ft)', 'End Loc. Full Width (Sta. ft)'],
                    'df_shoulder': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Start Slope (%)',
                                    'End Slope (%)', 'Start Width (ft)', 'End Width (ft)', 'Priority'],
                    'df_crossslope': ['Location (Sta. ft)', 'Cross Slope (%)'],
                    'df_median': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Start Width (ft)',
                                  'End Width (ft)'],
                    'df_hvs': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Year',
                               'Proportion of AADT with High Volume'],
                    'df_rampconn': ['Gore Location (Sta. ft)', 'Gore-Taper Length (ft)', 'Alignment Priority'],
                    'df_medianbarr': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)',
                                      'Start Offset of Median Barrier from Inside Traveled Way (ft)',
                                      'End Offset of Median Barrier from Inside Traveled Way (ft)'],
                    'df_outbarr': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)',
                                   'Start Offset of Outside Barrier from Outside Traveled Way (ft)',
                                   'End Offset of Outside Barrier from Outside Traveled Way (ft)'],
                    'df_clearzone': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Start Width of Clear Zone (ft)',
                                     'End Width of Clear Zone (ft)'],
                    'df_cmf': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Start CMF Year', 'End CMF Year',
                               'CMF Value']}

num_cols_dict_artseg = {'df_horiz': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Curve Radius (ft)',
                                     'Deflection Angle (deg)'],
                        'df_vert': ['VPI/Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Back Grade (%)',
                                    'Back Length (ft)', 'Forward Grade (%)', 'Forward Length (ft)'],
                        'df_areatype': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)'],
                        'df_funcclass': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)'],
                        'df_aadt': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Year', 'AADT (vpd)'],
                        'df_lane': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Priority',
                                    'Start Width (ft)', 'End Width (ft)'],
                        'df_twltl': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Start Centerline Offset (ft)',
                                     'End Centerline Offset (ft)', 'Begin Loc. Full Width (Sta. ft)',
                                     'End Loc. Full Width (Sta. ft)', 'Lane Width (ft)'],
                        'df_shoulder': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Start Slope (%)',
                                        'End Slope (%)', 'Start Width (ft)', 'End Width (ft)', 'Priority'],
                        'df_median': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Start Width (ft)',
                                      'End Width (ft)'],
                        'df_medianbarr': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)',
                                          'Start Offset of Median Barrier Offset from Inside Traveled Way (ft)',
                                          'End Offset of Median Barrier Offset from Inside Traveled Way (ft)'],
                        'df_postedspeed': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Speed Limit (mph)'],
                        'df_speedcat': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', ],
                        'df_driveway': ['Location (Sta. ft)'],
                        'df_rail': ['Location (Sta. ft)'],
                        'df_lighting': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', ],
                        'df_enforce': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', ],
                        'df_object': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Offset (ft)',
                                      'Density (fixed objects/mi)'],
                        'df_parking': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)'],
                        'df_cmf': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Start CMF Year', 'End CMF Year',
                                   'CMF Value']}

num_cols_dict_artint = {'df_int': ['Number of Legs', 'Crossroad Station'],
                        'df_leg': ['Leg Name', 'Leg Station'],
                        'df_cmf': ['Start CMF Year', 'End CMF Year', 'CMF Value']}

num_cols_dict_ramp = {'df_horiz': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Curve Radius (ft)',
                                   'Deflection Angle (deg)', 'Ave. Entering Speed (mph)'],
                      'df_vert': ['VPI/Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Back Grade (%)',
                                  'Back Length (ft)', 'Forward Grade (%)', 'Forward Length (ft)'],
                      'df_areatype': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)'],
                      'df_funcclass': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)'],
                      'df_aadt': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Year', 'AADT (vpd)'],
                      'df_lane': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Priority', 'Start Width (ft)',
                                  'End Width (ft)'],
                      'df_shoulder': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Start Slope (%)',
                                      'End Slope (%)', 'Start Width (ft)', 'End Width (ft)', 'Priority'],
                      'df_rampconn': ['Gore Location (Sta. ft)', 'Gore-Taper Length (ft)', 'Alignment Priority'],
                      'df_lbarrier': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)',
                                      'Start Leftside Barrier Offset from Leftside Traveled Way (ft)',
                                      'End Leftside Barrier Offset from Leftside Traveled Way (ft)'],
                      'df_rbarrier': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)',
                                      'Start Rightside Barrier Offset from Rightside Traveled Way (ft)',
                                      'End Rightside Barrier Offset from Rightside Traveled Way (ft)'],
                      'df_cmf': ['Start Loc. (Sta. ft)', 'End Loc. (Sta. ft)', 'Start CMF Year', 'End CMF Year',
                                 'CMF Value']}

num_cols_dict_rampterminal = {'df_int': ['Number of Driveways Outside Terminal'],
                              'df_leg': ['Leg Station', 'Skew Angle'],
                              'df_cmf': ['Start CMF Year', 'End CMF Year', 'CMF Value']}